
name: nwchem_docker

on:
  push:
  pull_request:
  release:
  schedule:
    - cron: '59 15 * * FRI'
  repository_dispatch:
    types: [backend_automation]
  workflow_dispatch:

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      # Expose matched filters as job 'folders' output variable
      folders: ${{ steps.filter.outputs.changes }}
    steps:
    - uses: actions/checkout@v2
    - name: choose_dockerfile_filter
      uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          nwchem-dev: 'nwchem-dev/*'
          builddebs.buster: 'builddebs.buster/*'
    - name: cleanup_nochange
      if: steps.filter.outputs.changes == '[]'
      run: echo "no change detected"
  docker_filter:
    needs: [changes]
    if: |
        (github.event_name != 'workflow_dispatch') && (github.event_name != 'schedule')
    strategy:
        fail-fast: false
        matrix:
          folder: ["${{ fromJSON(needs.changes.outputs.folders) }}", helloworld]
          archs: [linux/amd64, linux/arm64, linux/ppc64le, linux/arm/v7]
          exclude:
            - {folder: helloworld, archs: linux/arm64}
            - {folder: helloworld, archs: linux/ppc64le}
            - {folder: helloworld, archs: linux/arm/v7}
#            - folder: nwchem-701.mpipr.ifort
#              archs: linux/amd64

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Qemu
        uses: docker/setup-qemu-action@v1
        with:
          image: crazymax/binfmt:v6.0.0
      - name: Available platforms
        run: echo ${{ steps.qemu.outputs.platforms }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        if: ${{ github.actor == github.repository_owner }}
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Get Arch
        id: get-arch
        run: |
          echo "::set-output name=arch::$(echo ${{matrix.archs }} | sed 's/linux//'|sed  's/\///g' )"
        shell: bash
      - name: build_filter
        if: ${{ matrix.folder  != 'helloworld' }}
        uses: docker/build-push-action@v2
        with:
          push: ${{ github.actor == github.repository_owner }}
          context: ${{ matrix.folder }}
          platforms: ${{ matrix.archs }}
          tags: ghcr.io/${{ github.actor }}/${{ matrix.folder }}/${{ steps.get-arch.outputs.arch }}:latest
      - name: load and test image
        if:  ( github.actor == github.repository_owner ) && ( matrix.folder  != 'helloworld' )
        run: |
          docker pull ghcr.io/${{ github.actor }}/${{ matrix.folder }}/${{ steps.get-arch.outputs.arch }}
          cd /tmp
          umask u=rwx,g=rwx,o=rwx
          umask -S
          svn export https://github.com/nwchemgit/nwchem/trunk/QA >& svnout.log
          cd QA
          if [[ ${{ matrix.archs }} != 'linux/arm/v7' ]] ; then \
          docker run --rm --platform ${{matrix.archs }} \
          -e NWCHEM_EXECUTABLE=/opt/nwchem/bin/nwchem --entrypoint='/opt/nwchem/QA/runtests.mpi.unix' \
          -v `pwd`:/opt/nwchem/QA ghcr.io/${{ github.actor }}/${{ matrix.folder }}/${{ steps.get-arch.outputs.arch }} \
          dft_he2+ prop_mep_gcube cosmo_h2o_dft pyqa3 ;\
          fi
  docker_schedule:
    if: (github.event_name == 'workflow_dispatch') || (github.event_name == 'schedule')
    strategy:
        fail-fast: false
        matrix:
          folder:
            - nwchem-dev
          archs: [linux/amd64, linux/arm64, linux/ppc64le, linux/arm/v7]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Qemu
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          image: crazymax/binfmt:v6.0.0
      - name: Available platforms
        run: echo ${{ steps.qemu.outputs.platforms }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        if: ${{ github.actor == github.repository_owner }}
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Get Arch
        id: get-arch
        run: |
          echo "::set-output name=arch::$(echo ${{matrix.archs }} | sed 's/linux//'|sed  's/\///g' )"
        shell: bash
      - name: build_schedule
        uses: docker/build-push-action@v2
        with:
          push: ${{ github.actor == github.repository_owner }}
          context: ${{ matrix.folder }}
          platforms: ${{ matrix.archs }}
          tags: ghcr.io/${{ github.actor }}/${{ matrix.folder }}/${{ steps.get-arch.outputs.arch }}:latest
      - name: load and test image
        if: ${{ github.actor == github.repository_owner }}
        run: |
          docker pull ghcr.io/${{ github.actor }}/${{ matrix.folder }}/${{ steps.get-arch.outputs.arch }}
          cd /tmp
          umask u=rwx,g=rwx,o=rwx
          umask -S
          svn export https://github.com/nwchemgit/nwchem/trunk/QA >& svnout.log
          cd QA
          if [[ ${{ matrix.archs }} != 'linux/arm/v7'  ]] ; then \
          docker run --rm --platform ${{matrix.archs }} \
          -e NWCHEM_EXECUTABLE=/opt/nwchem/bin/nwchem --entrypoint='/opt/nwchem/QA/runtests.mpi.unix' \
          -v `pwd`:/opt/nwchem/QA ghcr.io/${{ github.actor }}/${{ matrix.folder }}/${{ steps.get-arch.outputs.arch }} \
          dft_he2+ prop_mep_gcube cosmo_h2o_dft pyqa3 ;\
          fi
